### ISSUE TITLE
Open on OSM 404s

### ISSUE THREAD

**Issue by edent** [Rudloff/openvegemap-editor#21]
Eg https://editor.openvegemap.netlib.re/way/153926021

The Open on OSM button goes to http://www.openstreetmap.org/restaurant/153926021 which is a 404 error.

**Comment by Rudloff** [comment]
Fixed in https://github.com/Rudloff/openvegemap-editor/commit/9c2cf24cb36ca1cdbca39aef9fbaa73db05eeef2.

**Comment by edent** [comment]
This doesn't seem to have fixed the issue.

e.g. https://editor.openvegemap.netlib.re/node/658959582 still goes to https://www.openstreetmap.org/restaurant/658959582

**Comment by Rudloff** [comment]
The fix will be included in the next release.
