### ISSUE TITLE
Only allow editing whitelisted-tags-bearing amenities

### ISSUE THREAD

**Issue by gileri** [Rudloff/openvegemap-editor#3]
Right now, the editor allow anonymous edits to OSM, which add diet tags to any node on OSM, based on it's address, event if the place does not provide food.

For example I can add diet info to [a city for example](https://editor.openvegemap.netlib.re/node/986924508)

To solve this, editions should be allowed only on existing amenities. Here are some tags indicating food-related amenities :

- amenity=restaurant
- amenity=pub
- amenity=bar
- shop=supermarket
- shop=convenience

After having created this list, there are multiple solution for limiting search/display results to those categories :

- Filter nominatim results (see the [extratag parameter](https://wiki.openstreetmap.org/wiki/Nominatim))
- Use overpass API to obtain the results based on a radius around the geocoded (via nominatim) address the user entered

I think it's wise to stop allowing new contributions until this is fixed.

**Comment by gileri** [comment]
Some offending changesets :

- https://www.openstreetmap.org/node/2636921678
- https://www.openstreetmap.org/node/3075857787

**Comment by Rudloff** [comment]
Hello,

I published [an update](https://github.com/Rudloff/openvegemap-editor/commit/1b920950375ff92a34a1724dac8708c3848950cf) that filters the search results.
Please tell me if you think I missed some valid tags.

**Comment by gileri** [comment]
I can see some :

shop :
- deli
- ice_cream
- pasta
- general
- supermarket

craft :
- confectionery

amenity :
- ice_cream

**Comment by Rudloff** [comment]
Thanks, I added them.
